### PR TITLE
compiler: more cleanup

### PR DESCRIPTION
**Pull request by georgebisbas**

### CODE REVIEW

**Review by PapyChacal — APPROVED** [review]
Looks good to me !
Not familiar with the tricky bits, but I guess we have CI to trust now 🙂

**Review by georgebisbas — COMMENTED** [review]
@PapyChacal I added some more commits; please have another look.

**Review by PapyChacal — APPROVED** [review]
Idem!
Really nice to see this cleaned up 😊

**Review by PapyChacal — APPROVED** [review]
Another approval after last commits!

**Pull request merged**
